version: '3.8'
services:
  bstore:
    image: projectb8/bstore:v2
    ports:
      - 8082:8082
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bstore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=8888
    volumes:
      - bstore-data:/var/lib/bstore


  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=8888
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bstore
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  pgdata:
  bstore-data:

