spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytestore
    username: postgres
    password: 8888

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update


  liquibase:
    enabled: true
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
    change-log: "db/changelog/db.changelog-main.yaml"

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

    host: smtp.gmail.com
    username: bytestoree8@gmail.com
    password: pwno cvcu fzjj isxi
    default-encoding: UTF-8
    protocol: smtp
    port: 587

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 983185016956-aaala8q58vmcp07jg840he3hbg1uldl7.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            tokenUri: https://oauth2.googleapis.com/token
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            userNameAttribute: email

server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: never
  port: 8082


cloud:
  aws:
    credentials:
      accessKey: AKIA45Y2RSZK3ATT2XGJ
      secretKey: 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
    region:
      static: us-east-1
    s3:
      bucket: bytestore-bucket

logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    com.yourpackage: DEBUG