spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/startapp
    username: postgres
    password: 8888


  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

  liquibase:
      enabled: true
      database-change-log-lock-table: DATABASECHANGELOGLOCK
      database-change-log-table: DATABASECHANGELOG
      change-log: "db/changelog/db.changelog-main.yaml"

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

    host: smtp.gmail.com
    username: nazrin.shikhalievaa@gmail.com
    password: gpzk qidl amjh nutw
    default-encoding: UTF-8
    protocol: smtp
    port: 587


  security:
    oauth2:
      client:
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - openid
              - profile
              - email

server:
  port: 8080
  servlet:
    context-path: /bytestore
